-- 스키마 생성 (이미 존재하면 생성하지 않음)
CREATE SCHEMA IF NOT EXISTS companies AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS products AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS inventories AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS livebroadcast AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS chats AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS orders AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS coupons AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS users AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS payments AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS notifications AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS ai_core AUTHORIZATION postgres;