-- create table companies.p_company
-- (
--     created_at timestamp(6),
--     created_by bigint,
--     deleted_at timestamp(6),
--     deleted_by bigint,
--     updated_at timestamp(6),
--     updated_by bigint,
--     hub_id     uuid,
--     id         uuid not null
--         primary key,
--     address    varchar(255),
--     name       varchar(255),
--     type       varchar(255)
--         constraint p_company_type_check
--             check ((type)::text = ANY ((ARRAY ['RECEIVER'::character varying, 'SUPPLIER'::character varying])::text[]))
-- );
--
-- alter table companies.p_company
--     owner to postgres;
--
-- create table deliveries.p_delivery
-- (
--     created_at        timestamp(6),
--     created_by        bigint,
--     deleted_at        timestamp(6),
--     deleted_by        bigint,
--     company_delivery_agent_id bigint,
--     hub_delivery_agent_id bigint,
--     updated_at        timestamp(6),
--     updated_by        bigint,
--     from_hub_id       uuid,
--     id                uuid         not null
--         primary key,
--     to_hub_id         uuid,
--     receive_name      varchar(50)  not null,
--     delivery_address  varchar(255) not null,
--     status            varchar(255) not null
--         constraint p_delivery_status_check
--             check ((status)::text = ANY
--                    ((ARRAY ['WAITING'::character varying, 'PENDING_HUB'::character varying, 'MOVE_TO_HUB'::character varying, 'ARRIVED_HUB'::character varying, 'OUT_FOR_DELIVERY'::character varying, 'MOVE_TO_COMPANY'::character varying, 'COMPLETED'::character varying])::text[]))
-- );
--
-- alter table deliveries.p_delivery
--     owner to postgres;
--
-- create table deliveries.p_delivery_agent
-- (
--     delivery_sequence integer,
--     created_at        timestamp(6),
--     created_by        bigint,
--     deleted_at        timestamp(6),
--     deleted_by        bigint,
--     updated_at        timestamp(6),
--     updated_by        bigint,
--     user_id           bigint       not null
--         primary key,
--     hub_id            uuid,
--     slack_id          varchar(255) not null,
--     type              varchar(255) not null
--         constraint p_delivery_agent_type_check
--             check ((type)::text = ANY ((ARRAY ['HUB'::character varying, 'COMPANY'::character varying])::text[]))
-- );
--
-- alter table deliveries.p_delivery_agent
--     owner to postgres;
--
-- create table deliveries.p_delivery_route
-- (
--     actual_distance           double precision not null,
--     actual_time               integer          not null,
--     estimated_distance        double precision not null,
--     estimated_time            integer          not null,
--     sequence                  integer          not null,
--     company_delivery_agent_id bigint,
--     created_at                timestamp(6),
--     created_by                bigint,
--     deleted_at                timestamp(6),
--     deleted_by                bigint,
--     hub_delivery_agent_id     bigint,
--     updated_at                timestamp(6),
--     updated_by                bigint,
--     delivery_id               uuid,
--     from_hub_id               uuid,
--     hub_route_id              uuid,
--     id                        uuid             not null
--         primary key,
--     to_hub_id                 uuid,
--     status                    varchar(255)     not null
--         constraint p_delivery_route_status_check
--             check ((status)::text = ANY
--         ((ARRAY ['WAITING'::character varying, 'PENDING_HUB'::character varying, 'MOVE_TO_HUB'::character varying, 'ARRIVED_HUB'::character varying, 'OUT_FOR_DELIVERY'::character varying, 'COMPLETED'::character varying, 'CANCELED'::character varying])::text[]))
--     );
--
-- alter table deliveries.p_delivery_route
--     owner to postgres;
--
-- create table hubs.p_hub
-- (
--     latitude    double precision not null,
--     longitude   double precision not null,
--     created_at  timestamp(6),
--     created_by  bigint,
--     deleted_at  timestamp(6),
--     deleted_by  bigint,
--     updated_at  timestamp(6),
--     updated_by  bigint,
--     id          uuid             not null   primary key,
--     hub_manager_user_id bigint,
--     hub_address varchar(255),
--     hub_name    varchar(255)
-- );
--
-- alter table hubs.p_hub
--     owner to postgres;
--
-- create table hubs.p_hub_manager
-- (
--     created_at timestamp(6),
--     created_by bigint,
--     deleted_at timestamp(6),
--     deleted_by bigint,
--     updated_at timestamp(6),
--     updated_by bigint,
--     user_id    bigint not null
--         unique,
--     hub_id     uuid,
--     id         uuid   not null
--         primary key
-- );
--
-- alter table hubs.p_hub_manager
--     owner to postgres;
--
-- create table hubs.p_hub_route
-- (
--     distance double precision not null,
--     duration integer,
--     created_at     timestamp(6),
--     created_by     bigint,
--     deleted_at     timestamp(6),
--     deleted_by     bigint,
--     updated_at     timestamp(6),
--     updated_by     bigint,
--     departure_hub_id    uuid,
--     id             uuid             not null
--         primary key,
--     arrival_hub_id      uuid
-- );
--
-- alter table hubs.p_hub_route
--     owner to postgres;
--
-- create table orders.p_order
-- (
--     quantity      integer      not null,
--     created_at    timestamp(6),
--     created_by    bigint,
--     deleted_at    timestamp(6),
--     deleted_by    bigint,
--     updated_at    timestamp(6),
--     updated_by    bigint,
--     user_id       bigint,
--     delivery_id   uuid         not null,
--     id            uuid         not null
--         primary key,
--     product_id    uuid         not null,
--     receiver_id   uuid         not null,
--     supplier_id   uuid         not null,
--     address       varchar(255) not null,
--     message       varchar(255) not null,
--     receiver_name varchar(255) not null,
--     status        varchar(255) not null
--         constraint p_order_status_check
--             check ((status)::text = ANY ((ARRAY ['SUCCESS'::character varying, 'FAIL'::character varying])::text[]))
--     );
--
-- alter table orders.p_order
--     owner to postgres;
--
-- create table products.p_product
-- (
--     quantity   integer,
--     created_at timestamp(6),
--     created_by bigint,
--     deleted_at timestamp(6),
--     deleted_by bigint,
--     updated_at timestamp(6),
--     updated_by bigint,
--     company_id uuid,
--     hub_id     uuid,
--     id         uuid not null
--         primary key,
--     name       varchar(255)
-- );
--
-- alter table products.p_product
--     owner to postgres;
--
-- create table users.p_users
-- (
--     created_at timestamp(6),
--     created_by bigint,
--     deleted_at timestamp(6),
--     deleted_by bigint,
--     id         bigint generated by default as identity
--         primary key,
--     updated_at timestamp(6),
--     updated_by bigint,
--     password   varchar(255) not null,
--     role       varchar(255) not null
--         constraint p_users_role_check
--             check ((role)::text = ANY
--         ((ARRAY ['DELIVERY_AGENT'::character varying, 'TRADE_PARTNER'::character varying, 'HUB_MANAGER'::character varying, 'MASTER'::character varying])::text[])),
--     slack_id   varchar(255) not null
--         unique,
--     username   varchar(255) not null
--         unique
-- );
--
-- alter table users.p_users
--     owner to postgres;
--
-- create table ai_core.slack
-- (
--     created_at     timestamp(6),
--     created_by     bigint,
--     deleted_at     timestamp(6),
--     deleted_by     bigint,
--     updated_at     timestamp(6),
--     updated_by     bigint,
--     id             uuid         not null
--         primary key,
--     message        text         not null,
--     message_status varchar(255)
--         constraint slack_message_status_check
--             check ((message_status)::text = ANY
--         ((ARRAY ['SENT'::character varying, 'FAILED'::character varying])::text[])),
--     slack_id       varchar(255) not null
-- );
--
-- alter table ai_core.slack
--     owner to postgres;
--
--
--
--
--
--
--
--
--
--
