server:
  port: 19091

spring:
  webflux:
    static-path-pattern: /swagger-ui/**
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      forwarded-headers-strategy: framework
      discovery: # 서비스 디스커버리를 통해 동적으로 라우트를 생성항도록 설정
        locator:
          enabled: true
        default-filters:
          - PreserveHostHeader=true # 헤더 유지
          - AddRequestHeader=Authorization, {Authorization}
      routes:
        - id: ai
          uri: lb://ai
          predicates:
            - Path=/api/v1/ai/**, /api-docs-ai

        - id: chat
          uri: lb://chat
          predicates:
            - Path=/api/v1/chattings/**, /api-docs-chat

        - id: company
          uri: lb://company
          predicates:
            - Path=/api/v1/companies/**, /api-docs-company

        - id: coupon
          uri: lb://coupon
          predicates:
            - Path=/api/v1/coupon-policies/**, /api/v1/issued-coupons/**, /api-docs-coupon

        - id: livebroadcast
          uri: lb://livebroadcast
          predicates:
            - Path=/api/v1/livebroadcasts/**, /api-docs-live-broadcast

        - id: notification
          uri: lb://notification
          predicates:
            - Path=/api/v1/notifications/**, /api-docs-notification

        - id: order
          uri: lb://order
          predicates:
            - Path=/api/v1/orders/**, /api-docs-order

        - id: payment
          uri: lb://payment
          predicates:
            - Path=/api/v1/payments/**, /api-docs-payment

        - id: product
          uri: lb://product
          predicates:
            - Path=/api/v1/products/**, /api/v1/inventories/**, /api-docs-product

        - id: user
          uri: lb://user
          predicates:
            - Path=/api/v1/users/**, /api/v1/auth/**, /v3/api-docs/user, /api-docs-user



eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

service:
  jwt:
    secret-key: ${JWT_SECRET_KEY}

#  service:
#    whitelist:
#      paths:
#        - "/auth/**"
#        - "/users/**"
#        - "/api-docs-user"
#        - "/api-docs-hub"
#        - "/api-docs-company"
#        - "/api-docs-product"
#        - "/api-docs-order"
#        - "/api-docs-delivery"
#        - "/api-docs-coupon"
#        - "/api-docs-payment"
#        - "/api-docs-chat"
#        - "/api-docs-ai"
#        - "/api-docs-notification"
#        - "/api-docs-live-broadcast"
#        - "/swagger-ui/**"
#        - "/swagger-ui.html"
#        - "/v3/api-docs/**"
#        - "/swagger-resources/**"
#        - "/webjars/**"

#springdoc:
#  swagger-ui:
#    path: /swagger-ui
#    urls:
#      - name: user
#        url: /v3/api-docs/user
#      - name: company
#        url: /api-docs-company
#      - name: coupon
#        url: /api-docs-coupon
#      - name: live-broadcast
#        url: /api-docs-live-broadcast
#      - name: notification
#        url: /api-docs-notification
#      - name: order
#        url: /api-docs-order
#      - name: payment
#        url: /api-docs-payment
#      - name: product
#        url: /api-docs-product
#      - name: chat
#        url: /api-docs-chat
#      - name: ai
#        url: /api-docs-ai
