server:
  port: 19110

spring:
  application:
    name: notification
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_schema: notifications
  datasource:
    url: jdbc:postgresql://localhost:5432/livecommerce
    username: postgres
    password: 8dostore
    driver-class-name: org.postgresql.Driver