server:
  port: 19110

spring:
  application:
    name: notification
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_schema: notifications
  datasource:
    url: jdbc:postgresql://localhost:5432/livecommerce
    username: postgres
    password: 8dostore
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9092  # 카프카 브로커 URL
    consumer:
      group-id: notification-group  # 소비자 그룹 ID (필요에 따라 설정)
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

management:
  endpoints:
    web:
      exposure:
        include: refresh

gateway:
  base-url: http://localhost:19091

springdoc:
  api-docs:
    path: /v3/api-docs/notification