server:
  port: 19070

spring:
  application:
    name: product
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_schema: products
  datasource:
    url: jdbc:postgresql://localhost:5432/livecommerce
    username: postgres
    password: 8dostore
    driver-class-name: org.postgresql.Driver
  redis:
    host: localhost
    port: 6379
  sql:
    init:
      mode: always
      data-locations: classpath:db/data.sql