server:
  port: 8761

spring:
  application:
    name: eureka

eureka:
  instance:
    instance-id: eureka:${server.port}
    hostname: eureka
    prefer-ip-address: false

  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka:8761/eureka/

  server:
    enable-self-preservation: false
    defaultOpenForTrafficCount: 0

management:
  endpoints:
    web:
      exposure:
        include: health, info, eureka, apps