server:
  port: 19090

spring:
  application:
    name: eureka

eureka:
  instance:
    instance-id: eureka:${server.port}
    hostname: eureka
    prefer-ip-address: false

  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka:19090/eureka/

  server:
    enable-self-preservation: false
    defaultOpenForTrafficCount: 0