server:
  port: 19070

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
management:
  endpoints:
    web:
      exposure:
        include: refresh

spring:
  application:
    name: product
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_schema: products
  datasource:
    url: jdbc:postgresql://localhost:5432/livecommerce
    username: postgres
    password: 8dostore
    driver-class-name: org.postgresql.Driver
  redis:
    host: localhost
    port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: >
          inventory-decrease:com.live_commerce.product.product.infrastructure.kafka.event.OrderRequestedInventoryEvent,
          inventory-decreased:com.live_commerce.product.product.infrastructure.kafka.event.InventoryDecreasedEvent,
          inventory-rollback:com.live_commerce.product.product.infrastructure.kafka.event.InventoryRollbackEvent

    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: >
          inventory-decrease:com.live_commerce.product.product.infrastructure.kafka.event.OrderRequestedInventoryEvent,
          inventory-decreased:com.live_commerce.product.product.infrastructure.kafka.event.InventoryDecreasedEvent,
          inventory-rollback:com.live_commerce.product.product.infrastructure.kafka.event.InventoryRollbackEvent
      listener:
        ack-mode: MANUAL_IMMEDIATE

gateway:
  base-url: http://localhost:19091

springdoc:
  api-docs:
    path: /v3/api-docs/product