spring:
  config:
    import: "configserver:http://localhost:18080"
  application:
    name: coupon
  profiles:
    active: dev

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.live_commerce.coupon.infrastructure.kafka.dto
        spring.json.value.default.type: com.live_commerce.coupon.infrastructure.kafka.dto.CouponUsedMessage
