spring:
  config:
    import: "configserver:http://localhost:18080"
  application:
    name: ai
  profiles:
    active: dev

feign:
  client:
    config:
      geminiClient:
        connectTimeout: 3000
        readTimeout: 30000

#spring:
#  profiles:
#    active: prod
#  cloud:
#    config:
#      enabled: false