server:
  port: 18080

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - file:/app/config-repo
#logging:
#  level:
#    root: INFO
#    feign: DEBUG
#    feign.client: DEBUG