spring:
  config:
    import: "configserver:http://localhost:18080"
  application:
    name: payment
  profiles:
    active: dev

payment:
  expire-minutes: 10

toss:
  pay:
    secret-key: ${TOSS_PAY_SECRET_KEY:test_sk_placeholder}

#spring:
#  profiles:
#    active: prod
#  cloud:
#    config:
#      enabled: false