spring:
  config:
    import: "configserver:http://localhost:18080"
  application:
    name: payment
  profiles:
    active: dev

payment:
  expire-minutes: 10

#spring:
#  profiles:
#    active: prod
#  cloud:
#    config:
#      enabled: false