spring:
  application:
    name: product
  profiles:
    active: dev
  config:
    import: "configserver:http://localhost:18080"

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

management:
  endpoints:
    web:
      exposure:
        include: refresh


#springdoc:
#  swagger-ui:
#    enabled: true
#    path: /docs
#    operations-sorter: alpha
#    tags-sorter: alpha
#  api-docs:
#    enabled: true
#    path: /v3/api-docs/user