spring:
  application:
    name: gateway
  profiles:
    active: dev
  config:
    import: "configserver:http://localhost:18080"  # Config Server ?? ??

server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

management:
  endpoints:
    web:
      exposure:
        include: refresh