server:
  port: 19110

eureka:
  client:
    service-url:
      defaultZone: http://eureka:19090/eureka/

spring:
  application:
    name: notification
  config:
    import: optional:file:.env[.properties]
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_schema: notifications
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: kafka:9092  # 카프카 브로커 URL
    consumer:
      group-id: notification-group  # 소비자 그룹 ID (필요에 따라 설정)
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer


management:
  endpoints:
    web:
      exposure:
        include: refresh
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

gateway:
  base-url: http://gateway:19091