spring:
  config:
    import: "configserver:http://localhost:18080"
  application:
    name: company
  profiles:
    active: dev

#spring:
#  profiles:
#    active: prod
#  cloud:
#    config:
#      enabled: false