spring:
  application:
    name: livebroadcast
  config:
    import: "optional:configserver:http://config:18080/"
  cloud:
    config:
      name: livebroadcast
      profile: prod
      fail-fast: true